### ISSUE TITLE
Import from Url

### ISSUE THREAD

**Issue by keranski** [miko3k/stasx#1]
Hello Peter! 

Really nice project - it is quite handy for personal password management!
 
When I tested 'stasx' I thought that it would be good if there is one additional option - to add/import 'stasx' file directly from Url. 

Let’s say I have an encrypted/password protected 'stasx' file somewhere (I may host that file literally everywhere - not only in my cloud service..., and it would be easily accessible at any time...).

If 'stasx' has an additional option – a Url input field and a button 'Import from Url' it would be really handy (otherwise I have to have my 'stasx' file downloaded on my PC or smartphone first and then to open it - if I don't want or I don't use Google Drive service...).

Is it possible to add that additional option - 'Import 'stasx' file from Url'??

Thanks and regards!

**Comment by miko3k** [comment]
Thanks for kind words!

However, import from URL is kinda hard to do, because it would require CORS to be properly configured on the other server.

Feel free to start hacking, obviously.
